package alex;

public enum ClaseLexica {
    MAIN, IDEN, ENT, CARACTER, CADENA, WHILE, IF, ELSE, END, PRINT, SWITCH, CASE, STRUCT, ENUM, BARTOLO, RETURN, 
    INT, VOID, CHAR, STRING, BOOL, TRUE, FALSE, PAP, PCIERRE, LAP, LCIERRE, CAP, CCIERRE, 
    IGUAL, PUNTO, COMA, PUNTOYCOMA, DOSPUNTOS,
    MASMAS, MAS, MENOSMENOS, MENOS, POR, DIV, MOD, AND, OR ,DESIG, NOT, IGIG, MAYIG, MAY, MENIG, MEN, EOF,
}
