
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu May 27 01:43:08 CEST 2021
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MASMAS = 36;
  public static final int DOSPUNTOS = 35;
  public static final int MENOSMENOS = 38;
  public static final int POR = 40;
  public static final int CHAR = 20;
  public static final int CCIERRE = 30;
  public static final int PUNTOYCOMA = 33;
  public static final int PCIERRE = 26;
  public static final int LCIERRE = 28;
  public static final int LAP = 27;
  public static final int CASE = 13;
  public static final int IGIG = 47;
  public static final int CAP = 29;
  public static final int INT = 18;
  public static final int NOT = 46;
  public static final int AND = 43;
  public static final int IGUAL = 31;
  public static final int CARACTER = 6;
  public static final int OR = 44;
  public static final int BOOL = 22;
  public static final int DIV = 41;
  public static final int MAIN = 2;
  public static final int IF = 8;
  public static final int EOF = 0;
  public static final int RETURN = 17;
  public static final int TRUE = 23;
  public static final int DESIG = 45;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int CADENA = 5;
  public static final int MENOS = 39;
  public static final int MOD = 42;
  public static final int VOID = 19;
  public static final int MENIG = 50;
  public static final int SWITCH = 12;
  public static final int ENT = 4;
  public static final int PAP = 25;
  public static final int ELSE = 9;
  public static final int PUNTO = 34;
  public static final int MAYIG = 48;
  public static final int MEN = 51;
  public static final int ENUM = 15;
  public static final int IDEN = 3;
  public static final int WHILE = 7;
  public static final int END = 10;
  public static final int STRING = 21;
  public static final int FALSE = 24;
  public static final int STRUCT = 14;
  public static final int MAY = 49;
  public static final int BARTOLO = 16;
  public static final int PRINT = 11;
  public static final int MAS = 37;
}

